name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install --prefix src

    - name: Install dependencies
      run: npm run start --prefix src
      

    - name: Run tests
      run: npm run test-integration --prefix src
      

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
